/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncbi-openapi-v2_goland

import (
	"encoding/json"
	"fmt"
)

// V2OrthologRequestContentType the model 'V2OrthologRequestContentType'
type V2OrthologRequestContentType string

// List of v2OrthologRequestContentType
const (
	V2ORTHOLOGREQUESTCONTENTTYPE_COMPLETE V2OrthologRequestContentType = "COMPLETE"
	V2ORTHOLOGREQUESTCONTENTTYPE_IDS_ONLY V2OrthologRequestContentType = "IDS_ONLY"
)

// All allowed values of V2OrthologRequestContentType enum
var AllowedV2OrthologRequestContentTypeEnumValues = []V2OrthologRequestContentType{
	"COMPLETE",
	"IDS_ONLY",
}

func (v *V2OrthologRequestContentType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V2OrthologRequestContentType(value)
	for _, existing := range AllowedV2OrthologRequestContentTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V2OrthologRequestContentType", value)
}

// NewV2OrthologRequestContentTypeFromValue returns a pointer to a valid V2OrthologRequestContentType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV2OrthologRequestContentTypeFromValue(v string) (*V2OrthologRequestContentType, error) {
	ev := V2OrthologRequestContentType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V2OrthologRequestContentType: valid values are %v", v, AllowedV2OrthologRequestContentTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V2OrthologRequestContentType) IsValid() bool {
	for _, existing := range AllowedV2OrthologRequestContentTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v2OrthologRequestContentType value
func (v V2OrthologRequestContentType) Ptr() *V2OrthologRequestContentType {
	return &v
}

type NullableV2OrthologRequestContentType struct {
	value *V2OrthologRequestContentType
	isSet bool
}

func (v NullableV2OrthologRequestContentType) Get() *V2OrthologRequestContentType {
	return v.value
}

func (v *NullableV2OrthologRequestContentType) Set(val *V2OrthologRequestContentType) {
	v.value = val
	v.isSet = true
}

func (v NullableV2OrthologRequestContentType) IsSet() bool {
	return v.isSet
}

func (v *NullableV2OrthologRequestContentType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2OrthologRequestContentType(val *V2OrthologRequestContentType) *NullableV2OrthologRequestContentType {
	return &NullableV2OrthologRequestContentType{value: val, isSet: true}
}

func (v NullableV2OrthologRequestContentType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2OrthologRequestContentType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

