/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V2TaxonomyFilteredSubtreeResponseEdgesEntry A map.
type V2TaxonomyFilteredSubtreeResponseEdgesEntry struct {
	Default *V2TaxonomyFilteredSubtreeResponseEdge `json:"default,omitempty"`
}

// NewV2TaxonomyFilteredSubtreeResponseEdgesEntry instantiates a new V2TaxonomyFilteredSubtreeResponseEdgesEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2TaxonomyFilteredSubtreeResponseEdgesEntry() *V2TaxonomyFilteredSubtreeResponseEdgesEntry {
	this := V2TaxonomyFilteredSubtreeResponseEdgesEntry{}
	return &this
}

// NewV2TaxonomyFilteredSubtreeResponseEdgesEntryWithDefaults instantiates a new V2TaxonomyFilteredSubtreeResponseEdgesEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2TaxonomyFilteredSubtreeResponseEdgesEntryWithDefaults() *V2TaxonomyFilteredSubtreeResponseEdgesEntry {
	this := V2TaxonomyFilteredSubtreeResponseEdgesEntry{}
	return &this
}

// GetDefault returns the Default field value if set, zero value otherwise.
func (o *V2TaxonomyFilteredSubtreeResponseEdgesEntry) GetDefault() V2TaxonomyFilteredSubtreeResponseEdge {
	if o == nil || o.Default == nil {
		var ret V2TaxonomyFilteredSubtreeResponseEdge
		return ret
	}
	return *o.Default
}

// GetDefaultOk returns a tuple with the Default field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2TaxonomyFilteredSubtreeResponseEdgesEntry) GetDefaultOk() (*V2TaxonomyFilteredSubtreeResponseEdge, bool) {
	if o == nil || o.Default == nil {
		return nil, false
	}
	return o.Default, true
}

// HasDefault returns a boolean if a field has been set.
func (o *V2TaxonomyFilteredSubtreeResponseEdgesEntry) HasDefault() bool {
	if o != nil && o.Default != nil {
		return true
	}

	return false
}

// SetDefault gets a reference to the given V2TaxonomyFilteredSubtreeResponseEdge and assigns it to the Default field.
func (o *V2TaxonomyFilteredSubtreeResponseEdgesEntry) SetDefault(v V2TaxonomyFilteredSubtreeResponseEdge) {
	o.Default = &v
}

func (o V2TaxonomyFilteredSubtreeResponseEdgesEntry) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Default != nil {
		toSerialize["default"] = o.Default
	}
	return json.Marshal(toSerialize)
}

type NullableV2TaxonomyFilteredSubtreeResponseEdgesEntry struct {
	value *V2TaxonomyFilteredSubtreeResponseEdgesEntry
	isSet bool
}

func (v NullableV2TaxonomyFilteredSubtreeResponseEdgesEntry) Get() *V2TaxonomyFilteredSubtreeResponseEdgesEntry {
	return v.value
}

func (v *NullableV2TaxonomyFilteredSubtreeResponseEdgesEntry) Set(val *V2TaxonomyFilteredSubtreeResponseEdgesEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableV2TaxonomyFilteredSubtreeResponseEdgesEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableV2TaxonomyFilteredSubtreeResponseEdgesEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2TaxonomyFilteredSubtreeResponseEdgesEntry(val *V2TaxonomyFilteredSubtreeResponseEdgesEntry) *NullableV2TaxonomyFilteredSubtreeResponseEdgesEntry {
	return &NullableV2TaxonomyFilteredSubtreeResponseEdgesEntry{value: val, isSet: true}
}

func (v NullableV2TaxonomyFilteredSubtreeResponseEdgesEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2TaxonomyFilteredSubtreeResponseEdgesEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


