/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// V2AnnotationForOrganelleType the model 'V2AnnotationForOrganelleType'
type V2AnnotationForOrganelleType string

// List of v2AnnotationForOrganelleType
const (
	V2ANNOTATIONFORORGANELLETYPE_GENOME_FASTA V2AnnotationForOrganelleType = "GENOME_FASTA"
	V2ANNOTATIONFORORGANELLETYPE_CDS_FASTA V2AnnotationForOrganelleType = "CDS_FASTA"
	V2ANNOTATIONFORORGANELLETYPE_PROTEIN_FASTA V2AnnotationForOrganelleType = "PROTEIN_FASTA"
)

// All allowed values of V2AnnotationForOrganelleType enum
var AllowedV2AnnotationForOrganelleTypeEnumValues = []V2AnnotationForOrganelleType{
	"GENOME_FASTA",
	"CDS_FASTA",
	"PROTEIN_FASTA",
}

func (v *V2AnnotationForOrganelleType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V2AnnotationForOrganelleType(value)
	for _, existing := range AllowedV2AnnotationForOrganelleTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V2AnnotationForOrganelleType", value)
}

// NewV2AnnotationForOrganelleTypeFromValue returns a pointer to a valid V2AnnotationForOrganelleType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV2AnnotationForOrganelleTypeFromValue(v string) (*V2AnnotationForOrganelleType, error) {
	ev := V2AnnotationForOrganelleType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V2AnnotationForOrganelleType: valid values are %v", v, AllowedV2AnnotationForOrganelleTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V2AnnotationForOrganelleType) IsValid() bool {
	for _, existing := range AllowedV2AnnotationForOrganelleTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v2AnnotationForOrganelleType value
func (v V2AnnotationForOrganelleType) Ptr() *V2AnnotationForOrganelleType {
	return &v
}

type NullableV2AnnotationForOrganelleType struct {
	value *V2AnnotationForOrganelleType
	isSet bool
}

func (v NullableV2AnnotationForOrganelleType) Get() *V2AnnotationForOrganelleType {
	return v.value
}

func (v *NullableV2AnnotationForOrganelleType) Set(val *V2AnnotationForOrganelleType) {
	v.value = val
	v.isSet = true
}

func (v NullableV2AnnotationForOrganelleType) IsSet() bool {
	return v.isSet
}

func (v *NullableV2AnnotationForOrganelleType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2AnnotationForOrganelleType(val *V2AnnotationForOrganelleType) *NullableV2AnnotationForOrganelleType {
	return &NullableV2AnnotationForOrganelleType{value: val, isSet: true}
}

func (v NullableV2AnnotationForOrganelleType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2AnnotationForOrganelleType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

