/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncbi-openapi-v2_goland

import (
	"encoding/json"
)

// V2VirusAvailabilityRequest struct for V2VirusAvailabilityRequest
type V2VirusAvailabilityRequest struct {
	Accessions []string `json:"accessions,omitempty"`
}

// NewV2VirusAvailabilityRequest instantiates a new V2VirusAvailabilityRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2VirusAvailabilityRequest() *V2VirusAvailabilityRequest {
	this := V2VirusAvailabilityRequest{}
	return &this
}

// NewV2VirusAvailabilityRequestWithDefaults instantiates a new V2VirusAvailabilityRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2VirusAvailabilityRequestWithDefaults() *V2VirusAvailabilityRequest {
	this := V2VirusAvailabilityRequest{}
	return &this
}

// GetAccessions returns the Accessions field value if set, zero value otherwise.
func (o *V2VirusAvailabilityRequest) GetAccessions() []string {
	if o == nil || o.Accessions == nil {
		var ret []string
		return ret
	}
	return o.Accessions
}

// GetAccessionsOk returns a tuple with the Accessions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2VirusAvailabilityRequest) GetAccessionsOk() ([]string, bool) {
	if o == nil || o.Accessions == nil {
		return nil, false
	}
	return o.Accessions, true
}

// HasAccessions returns a boolean if a field has been set.
func (o *V2VirusAvailabilityRequest) HasAccessions() bool {
	if o != nil && o.Accessions != nil {
		return true
	}

	return false
}

// SetAccessions gets a reference to the given []string and assigns it to the Accessions field.
func (o *V2VirusAvailabilityRequest) SetAccessions(v []string) {
	o.Accessions = v
}

func (o V2VirusAvailabilityRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Accessions != nil {
		toSerialize["accessions"] = o.Accessions
	}
	return json.Marshal(toSerialize)
}

type NullableV2VirusAvailabilityRequest struct {
	value *V2VirusAvailabilityRequest
	isSet bool
}

func (v NullableV2VirusAvailabilityRequest) Get() *V2VirusAvailabilityRequest {
	return v.value
}

func (v *NullableV2VirusAvailabilityRequest) Set(val *V2VirusAvailabilityRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV2VirusAvailabilityRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV2VirusAvailabilityRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2VirusAvailabilityRequest(val *V2VirusAvailabilityRequest) *NullableV2VirusAvailabilityRequest {
	return &NullableV2VirusAvailabilityRequest{value: val, isSet: true}
}

func (v NullableV2VirusAvailabilityRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2VirusAvailabilityRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


