/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V2GeneLinksRequest struct for V2GeneLinksRequest
type V2GeneLinksRequest struct {
	GeneIds []int32 `json:"gene_ids,omitempty"`
}

// NewV2GeneLinksRequest instantiates a new V2GeneLinksRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2GeneLinksRequest() *V2GeneLinksRequest {
	this := V2GeneLinksRequest{}
	return &this
}

// NewV2GeneLinksRequestWithDefaults instantiates a new V2GeneLinksRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2GeneLinksRequestWithDefaults() *V2GeneLinksRequest {
	this := V2GeneLinksRequest{}
	return &this
}

// GetGeneIds returns the GeneIds field value if set, zero value otherwise.
func (o *V2GeneLinksRequest) GetGeneIds() []int32 {
	if o == nil || o.GeneIds == nil {
		var ret []int32
		return ret
	}
	return o.GeneIds
}

// GetGeneIdsOk returns a tuple with the GeneIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2GeneLinksRequest) GetGeneIdsOk() ([]int32, bool) {
	if o == nil || o.GeneIds == nil {
		return nil, false
	}
	return o.GeneIds, true
}

// HasGeneIds returns a boolean if a field has been set.
func (o *V2GeneLinksRequest) HasGeneIds() bool {
	if o != nil && o.GeneIds != nil {
		return true
	}

	return false
}

// SetGeneIds gets a reference to the given []int32 and assigns it to the GeneIds field.
func (o *V2GeneLinksRequest) SetGeneIds(v []int32) {
	o.GeneIds = v
}

func (o V2GeneLinksRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.GeneIds != nil {
		toSerialize["gene_ids"] = o.GeneIds
	}
	return json.Marshal(toSerialize)
}

type NullableV2GeneLinksRequest struct {
	value *V2GeneLinksRequest
	isSet bool
}

func (v NullableV2GeneLinksRequest) Get() *V2GeneLinksRequest {
	return v.value
}

func (v *NullableV2GeneLinksRequest) Set(val *V2GeneLinksRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV2GeneLinksRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV2GeneLinksRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2GeneLinksRequest(val *V2GeneLinksRequest) *NullableV2GeneLinksRequest {
	return &NullableV2GeneLinksRequest{value: val, isSet: true}
}

func (v NullableV2GeneLinksRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2GeneLinksRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


