/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V2reportsFeatureCounts struct for V2reportsFeatureCounts
type V2reportsFeatureCounts struct {
	GeneCounts *V2reportsGeneCounts `json:"gene_counts,omitempty"`
}

// NewV2reportsFeatureCounts instantiates a new V2reportsFeatureCounts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2reportsFeatureCounts() *V2reportsFeatureCounts {
	this := V2reportsFeatureCounts{}
	return &this
}

// NewV2reportsFeatureCountsWithDefaults instantiates a new V2reportsFeatureCounts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2reportsFeatureCountsWithDefaults() *V2reportsFeatureCounts {
	this := V2reportsFeatureCounts{}
	return &this
}

// GetGeneCounts returns the GeneCounts field value if set, zero value otherwise.
func (o *V2reportsFeatureCounts) GetGeneCounts() V2reportsGeneCounts {
	if o == nil || o.GeneCounts == nil {
		var ret V2reportsGeneCounts
		return ret
	}
	return *o.GeneCounts
}

// GetGeneCountsOk returns a tuple with the GeneCounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2reportsFeatureCounts) GetGeneCountsOk() (*V2reportsGeneCounts, bool) {
	if o == nil || o.GeneCounts == nil {
		return nil, false
	}
	return o.GeneCounts, true
}

// HasGeneCounts returns a boolean if a field has been set.
func (o *V2reportsFeatureCounts) HasGeneCounts() bool {
	if o != nil && o.GeneCounts != nil {
		return true
	}

	return false
}

// SetGeneCounts gets a reference to the given V2reportsGeneCounts and assigns it to the GeneCounts field.
func (o *V2reportsFeatureCounts) SetGeneCounts(v V2reportsGeneCounts) {
	o.GeneCounts = &v
}

func (o V2reportsFeatureCounts) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.GeneCounts != nil {
		toSerialize["gene_counts"] = o.GeneCounts
	}
	return json.Marshal(toSerialize)
}

type NullableV2reportsFeatureCounts struct {
	value *V2reportsFeatureCounts
	isSet bool
}

func (v NullableV2reportsFeatureCounts) Get() *V2reportsFeatureCounts {
	return v.value
}

func (v *NullableV2reportsFeatureCounts) Set(val *V2reportsFeatureCounts) {
	v.value = val
	v.isSet = true
}

func (v NullableV2reportsFeatureCounts) IsSet() bool {
	return v.isSet
}

func (v *NullableV2reportsFeatureCounts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2reportsFeatureCounts(val *V2reportsFeatureCounts) *NullableV2reportsFeatureCounts {
	return &NullableV2reportsFeatureCounts{value: val, isSet: true}
}

func (v NullableV2reportsFeatureCounts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2reportsFeatureCounts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


