/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V2reportsWarning struct for V2reportsWarning
type V2reportsWarning struct {
	GeneWarningCode *V2reportsWarningGeneWarningCode `json:"gene_warning_code,omitempty"`
	Reason *string `json:"reason,omitempty"`
	Message *string `json:"message,omitempty"`
	ReplacedId *V2reportsWarningReplacedId `json:"replaced_id,omitempty"`
	UnrecognizedIdentifier *string `json:"unrecognized_identifier,omitempty"`
}

// NewV2reportsWarning instantiates a new V2reportsWarning object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2reportsWarning() *V2reportsWarning {
	this := V2reportsWarning{}
	var geneWarningCode V2reportsWarningGeneWarningCode = V2REPORTSWARNINGGENEWARNINGCODE_UNKNOWN_GENE_WARNING_CODE
	this.GeneWarningCode = &geneWarningCode
	return &this
}

// NewV2reportsWarningWithDefaults instantiates a new V2reportsWarning object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2reportsWarningWithDefaults() *V2reportsWarning {
	this := V2reportsWarning{}
	var geneWarningCode V2reportsWarningGeneWarningCode = V2REPORTSWARNINGGENEWARNINGCODE_UNKNOWN_GENE_WARNING_CODE
	this.GeneWarningCode = &geneWarningCode
	return &this
}

// GetGeneWarningCode returns the GeneWarningCode field value if set, zero value otherwise.
func (o *V2reportsWarning) GetGeneWarningCode() V2reportsWarningGeneWarningCode {
	if o == nil || o.GeneWarningCode == nil {
		var ret V2reportsWarningGeneWarningCode
		return ret
	}
	return *o.GeneWarningCode
}

// GetGeneWarningCodeOk returns a tuple with the GeneWarningCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2reportsWarning) GetGeneWarningCodeOk() (*V2reportsWarningGeneWarningCode, bool) {
	if o == nil || o.GeneWarningCode == nil {
		return nil, false
	}
	return o.GeneWarningCode, true
}

// HasGeneWarningCode returns a boolean if a field has been set.
func (o *V2reportsWarning) HasGeneWarningCode() bool {
	if o != nil && o.GeneWarningCode != nil {
		return true
	}

	return false
}

// SetGeneWarningCode gets a reference to the given V2reportsWarningGeneWarningCode and assigns it to the GeneWarningCode field.
func (o *V2reportsWarning) SetGeneWarningCode(v V2reportsWarningGeneWarningCode) {
	o.GeneWarningCode = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *V2reportsWarning) GetReason() string {
	if o == nil || o.Reason == nil {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2reportsWarning) GetReasonOk() (*string, bool) {
	if o == nil || o.Reason == nil {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *V2reportsWarning) HasReason() bool {
	if o != nil && o.Reason != nil {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *V2reportsWarning) SetReason(v string) {
	o.Reason = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *V2reportsWarning) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2reportsWarning) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *V2reportsWarning) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *V2reportsWarning) SetMessage(v string) {
	o.Message = &v
}

// GetReplacedId returns the ReplacedId field value if set, zero value otherwise.
func (o *V2reportsWarning) GetReplacedId() V2reportsWarningReplacedId {
	if o == nil || o.ReplacedId == nil {
		var ret V2reportsWarningReplacedId
		return ret
	}
	return *o.ReplacedId
}

// GetReplacedIdOk returns a tuple with the ReplacedId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2reportsWarning) GetReplacedIdOk() (*V2reportsWarningReplacedId, bool) {
	if o == nil || o.ReplacedId == nil {
		return nil, false
	}
	return o.ReplacedId, true
}

// HasReplacedId returns a boolean if a field has been set.
func (o *V2reportsWarning) HasReplacedId() bool {
	if o != nil && o.ReplacedId != nil {
		return true
	}

	return false
}

// SetReplacedId gets a reference to the given V2reportsWarningReplacedId and assigns it to the ReplacedId field.
func (o *V2reportsWarning) SetReplacedId(v V2reportsWarningReplacedId) {
	o.ReplacedId = &v
}

// GetUnrecognizedIdentifier returns the UnrecognizedIdentifier field value if set, zero value otherwise.
func (o *V2reportsWarning) GetUnrecognizedIdentifier() string {
	if o == nil || o.UnrecognizedIdentifier == nil {
		var ret string
		return ret
	}
	return *o.UnrecognizedIdentifier
}

// GetUnrecognizedIdentifierOk returns a tuple with the UnrecognizedIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2reportsWarning) GetUnrecognizedIdentifierOk() (*string, bool) {
	if o == nil || o.UnrecognizedIdentifier == nil {
		return nil, false
	}
	return o.UnrecognizedIdentifier, true
}

// HasUnrecognizedIdentifier returns a boolean if a field has been set.
func (o *V2reportsWarning) HasUnrecognizedIdentifier() bool {
	if o != nil && o.UnrecognizedIdentifier != nil {
		return true
	}

	return false
}

// SetUnrecognizedIdentifier gets a reference to the given string and assigns it to the UnrecognizedIdentifier field.
func (o *V2reportsWarning) SetUnrecognizedIdentifier(v string) {
	o.UnrecognizedIdentifier = &v
}

func (o V2reportsWarning) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.GeneWarningCode != nil {
		toSerialize["gene_warning_code"] = o.GeneWarningCode
	}
	if o.Reason != nil {
		toSerialize["reason"] = o.Reason
	}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	if o.ReplacedId != nil {
		toSerialize["replaced_id"] = o.ReplacedId
	}
	if o.UnrecognizedIdentifier != nil {
		toSerialize["unrecognized_identifier"] = o.UnrecognizedIdentifier
	}
	return json.Marshal(toSerialize)
}

type NullableV2reportsWarning struct {
	value *V2reportsWarning
	isSet bool
}

func (v NullableV2reportsWarning) Get() *V2reportsWarning {
	return v.value
}

func (v *NullableV2reportsWarning) Set(val *V2reportsWarning) {
	v.value = val
	v.isSet = true
}

func (v NullableV2reportsWarning) IsSet() bool {
	return v.isSet
}

func (v *NullableV2reportsWarning) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2reportsWarning(val *V2reportsWarning) *NullableV2reportsWarning {
	return &NullableV2reportsWarning{value: val, isSet: true}
}

func (v NullableV2reportsWarning) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2reportsWarning) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


