/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V2TaxonomyImageMetadataRequest struct for V2TaxonomyImageMetadataRequest
type V2TaxonomyImageMetadataRequest struct {
	Taxon *string `json:"taxon,omitempty"`
}

// NewV2TaxonomyImageMetadataRequest instantiates a new V2TaxonomyImageMetadataRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2TaxonomyImageMetadataRequest() *V2TaxonomyImageMetadataRequest {
	this := V2TaxonomyImageMetadataRequest{}
	return &this
}

// NewV2TaxonomyImageMetadataRequestWithDefaults instantiates a new V2TaxonomyImageMetadataRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2TaxonomyImageMetadataRequestWithDefaults() *V2TaxonomyImageMetadataRequest {
	this := V2TaxonomyImageMetadataRequest{}
	return &this
}

// GetTaxon returns the Taxon field value if set, zero value otherwise.
func (o *V2TaxonomyImageMetadataRequest) GetTaxon() string {
	if o == nil || o.Taxon == nil {
		var ret string
		return ret
	}
	return *o.Taxon
}

// GetTaxonOk returns a tuple with the Taxon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2TaxonomyImageMetadataRequest) GetTaxonOk() (*string, bool) {
	if o == nil || o.Taxon == nil {
		return nil, false
	}
	return o.Taxon, true
}

// HasTaxon returns a boolean if a field has been set.
func (o *V2TaxonomyImageMetadataRequest) HasTaxon() bool {
	if o != nil && o.Taxon != nil {
		return true
	}

	return false
}

// SetTaxon gets a reference to the given string and assigns it to the Taxon field.
func (o *V2TaxonomyImageMetadataRequest) SetTaxon(v string) {
	o.Taxon = &v
}

func (o V2TaxonomyImageMetadataRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Taxon != nil {
		toSerialize["taxon"] = o.Taxon
	}
	return json.Marshal(toSerialize)
}

type NullableV2TaxonomyImageMetadataRequest struct {
	value *V2TaxonomyImageMetadataRequest
	isSet bool
}

func (v NullableV2TaxonomyImageMetadataRequest) Get() *V2TaxonomyImageMetadataRequest {
	return v.value
}

func (v *NullableV2TaxonomyImageMetadataRequest) Set(val *V2TaxonomyImageMetadataRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV2TaxonomyImageMetadataRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV2TaxonomyImageMetadataRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2TaxonomyImageMetadataRequest(val *V2TaxonomyImageMetadataRequest) *NullableV2TaxonomyImageMetadataRequest {
	return &NullableV2TaxonomyImageMetadataRequest{value: val, isSet: true}
}

func (v NullableV2TaxonomyImageMetadataRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2TaxonomyImageMetadataRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


