/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncbi-openapi-v2_goland

import (
	"encoding/json"
)

// V2OrganismQueryRequest struct for V2OrganismQueryRequest
type V2OrganismQueryRequest struct {
	OrganismQuery *string `json:"organism_query,omitempty"`
	TaxonQuery *string `json:"taxon_query,omitempty"`
	TaxRankFilter *V2OrganismQueryRequestTaxRankFilter `json:"tax_rank_filter,omitempty"`
	TaxonResourceFilter *V2OrganismQueryRequestTaxonResourceFilter `json:"taxon_resource_filter,omitempty"`
	ExactMatch *bool `json:"exact_match,omitempty"`
}

// NewV2OrganismQueryRequest instantiates a new V2OrganismQueryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2OrganismQueryRequest() *V2OrganismQueryRequest {
	this := V2OrganismQueryRequest{}
	var taxRankFilter V2OrganismQueryRequestTaxRankFilter = V2ORGANISMQUERYREQUESTTAXRANKFILTER_SPECIES
	this.TaxRankFilter = &taxRankFilter
	var taxonResourceFilter V2OrganismQueryRequestTaxonResourceFilter = V2ORGANISMQUERYREQUESTTAXONRESOURCEFILTER_ALL
	this.TaxonResourceFilter = &taxonResourceFilter
	return &this
}

// NewV2OrganismQueryRequestWithDefaults instantiates a new V2OrganismQueryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2OrganismQueryRequestWithDefaults() *V2OrganismQueryRequest {
	this := V2OrganismQueryRequest{}
	var taxRankFilter V2OrganismQueryRequestTaxRankFilter = V2ORGANISMQUERYREQUESTTAXRANKFILTER_SPECIES
	this.TaxRankFilter = &taxRankFilter
	var taxonResourceFilter V2OrganismQueryRequestTaxonResourceFilter = V2ORGANISMQUERYREQUESTTAXONRESOURCEFILTER_ALL
	this.TaxonResourceFilter = &taxonResourceFilter
	return &this
}

// GetOrganismQuery returns the OrganismQuery field value if set, zero value otherwise.
func (o *V2OrganismQueryRequest) GetOrganismQuery() string {
	if o == nil || o.OrganismQuery == nil {
		var ret string
		return ret
	}
	return *o.OrganismQuery
}

// GetOrganismQueryOk returns a tuple with the OrganismQuery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2OrganismQueryRequest) GetOrganismQueryOk() (*string, bool) {
	if o == nil || o.OrganismQuery == nil {
		return nil, false
	}
	return o.OrganismQuery, true
}

// HasOrganismQuery returns a boolean if a field has been set.
func (o *V2OrganismQueryRequest) HasOrganismQuery() bool {
	if o != nil && o.OrganismQuery != nil {
		return true
	}

	return false
}

// SetOrganismQuery gets a reference to the given string and assigns it to the OrganismQuery field.
func (o *V2OrganismQueryRequest) SetOrganismQuery(v string) {
	o.OrganismQuery = &v
}

// GetTaxonQuery returns the TaxonQuery field value if set, zero value otherwise.
func (o *V2OrganismQueryRequest) GetTaxonQuery() string {
	if o == nil || o.TaxonQuery == nil {
		var ret string
		return ret
	}
	return *o.TaxonQuery
}

// GetTaxonQueryOk returns a tuple with the TaxonQuery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2OrganismQueryRequest) GetTaxonQueryOk() (*string, bool) {
	if o == nil || o.TaxonQuery == nil {
		return nil, false
	}
	return o.TaxonQuery, true
}

// HasTaxonQuery returns a boolean if a field has been set.
func (o *V2OrganismQueryRequest) HasTaxonQuery() bool {
	if o != nil && o.TaxonQuery != nil {
		return true
	}

	return false
}

// SetTaxonQuery gets a reference to the given string and assigns it to the TaxonQuery field.
func (o *V2OrganismQueryRequest) SetTaxonQuery(v string) {
	o.TaxonQuery = &v
}

// GetTaxRankFilter returns the TaxRankFilter field value if set, zero value otherwise.
func (o *V2OrganismQueryRequest) GetTaxRankFilter() V2OrganismQueryRequestTaxRankFilter {
	if o == nil || o.TaxRankFilter == nil {
		var ret V2OrganismQueryRequestTaxRankFilter
		return ret
	}
	return *o.TaxRankFilter
}

// GetTaxRankFilterOk returns a tuple with the TaxRankFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2OrganismQueryRequest) GetTaxRankFilterOk() (*V2OrganismQueryRequestTaxRankFilter, bool) {
	if o == nil || o.TaxRankFilter == nil {
		return nil, false
	}
	return o.TaxRankFilter, true
}

// HasTaxRankFilter returns a boolean if a field has been set.
func (o *V2OrganismQueryRequest) HasTaxRankFilter() bool {
	if o != nil && o.TaxRankFilter != nil {
		return true
	}

	return false
}

// SetTaxRankFilter gets a reference to the given V2OrganismQueryRequestTaxRankFilter and assigns it to the TaxRankFilter field.
func (o *V2OrganismQueryRequest) SetTaxRankFilter(v V2OrganismQueryRequestTaxRankFilter) {
	o.TaxRankFilter = &v
}

// GetTaxonResourceFilter returns the TaxonResourceFilter field value if set, zero value otherwise.
func (o *V2OrganismQueryRequest) GetTaxonResourceFilter() V2OrganismQueryRequestTaxonResourceFilter {
	if o == nil || o.TaxonResourceFilter == nil {
		var ret V2OrganismQueryRequestTaxonResourceFilter
		return ret
	}
	return *o.TaxonResourceFilter
}

// GetTaxonResourceFilterOk returns a tuple with the TaxonResourceFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2OrganismQueryRequest) GetTaxonResourceFilterOk() (*V2OrganismQueryRequestTaxonResourceFilter, bool) {
	if o == nil || o.TaxonResourceFilter == nil {
		return nil, false
	}
	return o.TaxonResourceFilter, true
}

// HasTaxonResourceFilter returns a boolean if a field has been set.
func (o *V2OrganismQueryRequest) HasTaxonResourceFilter() bool {
	if o != nil && o.TaxonResourceFilter != nil {
		return true
	}

	return false
}

// SetTaxonResourceFilter gets a reference to the given V2OrganismQueryRequestTaxonResourceFilter and assigns it to the TaxonResourceFilter field.
func (o *V2OrganismQueryRequest) SetTaxonResourceFilter(v V2OrganismQueryRequestTaxonResourceFilter) {
	o.TaxonResourceFilter = &v
}

// GetExactMatch returns the ExactMatch field value if set, zero value otherwise.
func (o *V2OrganismQueryRequest) GetExactMatch() bool {
	if o == nil || o.ExactMatch == nil {
		var ret bool
		return ret
	}
	return *o.ExactMatch
}

// GetExactMatchOk returns a tuple with the ExactMatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2OrganismQueryRequest) GetExactMatchOk() (*bool, bool) {
	if o == nil || o.ExactMatch == nil {
		return nil, false
	}
	return o.ExactMatch, true
}

// HasExactMatch returns a boolean if a field has been set.
func (o *V2OrganismQueryRequest) HasExactMatch() bool {
	if o != nil && o.ExactMatch != nil {
		return true
	}

	return false
}

// SetExactMatch gets a reference to the given bool and assigns it to the ExactMatch field.
func (o *V2OrganismQueryRequest) SetExactMatch(v bool) {
	o.ExactMatch = &v
}

func (o V2OrganismQueryRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.OrganismQuery != nil {
		toSerialize["organism_query"] = o.OrganismQuery
	}
	if o.TaxonQuery != nil {
		toSerialize["taxon_query"] = o.TaxonQuery
	}
	if o.TaxRankFilter != nil {
		toSerialize["tax_rank_filter"] = o.TaxRankFilter
	}
	if o.TaxonResourceFilter != nil {
		toSerialize["taxon_resource_filter"] = o.TaxonResourceFilter
	}
	if o.ExactMatch != nil {
		toSerialize["exact_match"] = o.ExactMatch
	}
	return json.Marshal(toSerialize)
}

type NullableV2OrganismQueryRequest struct {
	value *V2OrganismQueryRequest
	isSet bool
}

func (v NullableV2OrganismQueryRequest) Get() *V2OrganismQueryRequest {
	return v.value
}

func (v *NullableV2OrganismQueryRequest) Set(val *V2OrganismQueryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV2OrganismQueryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV2OrganismQueryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2OrganismQueryRequest(val *V2OrganismQueryRequest) *NullableV2OrganismQueryRequest {
	return &NullableV2OrganismQueryRequest{value: val, isSet: true}
}

func (v NullableV2OrganismQueryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2OrganismQueryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


