/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncbi-openapi-v2_goland

import (
	"encoding/json"
)

// V2VirusAvailability struct for V2VirusAvailability
type V2VirusAvailability struct {
	ValidAccessions []string `json:"valid_accessions,omitempty"`
	InvalidAccessions []string `json:"invalid_accessions,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewV2VirusAvailability instantiates a new V2VirusAvailability object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2VirusAvailability() *V2VirusAvailability {
	this := V2VirusAvailability{}
	return &this
}

// NewV2VirusAvailabilityWithDefaults instantiates a new V2VirusAvailability object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2VirusAvailabilityWithDefaults() *V2VirusAvailability {
	this := V2VirusAvailability{}
	return &this
}

// GetValidAccessions returns the ValidAccessions field value if set, zero value otherwise.
func (o *V2VirusAvailability) GetValidAccessions() []string {
	if o == nil || o.ValidAccessions == nil {
		var ret []string
		return ret
	}
	return o.ValidAccessions
}

// GetValidAccessionsOk returns a tuple with the ValidAccessions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2VirusAvailability) GetValidAccessionsOk() ([]string, bool) {
	if o == nil || o.ValidAccessions == nil {
		return nil, false
	}
	return o.ValidAccessions, true
}

// HasValidAccessions returns a boolean if a field has been set.
func (o *V2VirusAvailability) HasValidAccessions() bool {
	if o != nil && o.ValidAccessions != nil {
		return true
	}

	return false
}

// SetValidAccessions gets a reference to the given []string and assigns it to the ValidAccessions field.
func (o *V2VirusAvailability) SetValidAccessions(v []string) {
	o.ValidAccessions = v
}

// GetInvalidAccessions returns the InvalidAccessions field value if set, zero value otherwise.
func (o *V2VirusAvailability) GetInvalidAccessions() []string {
	if o == nil || o.InvalidAccessions == nil {
		var ret []string
		return ret
	}
	return o.InvalidAccessions
}

// GetInvalidAccessionsOk returns a tuple with the InvalidAccessions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2VirusAvailability) GetInvalidAccessionsOk() ([]string, bool) {
	if o == nil || o.InvalidAccessions == nil {
		return nil, false
	}
	return o.InvalidAccessions, true
}

// HasInvalidAccessions returns a boolean if a field has been set.
func (o *V2VirusAvailability) HasInvalidAccessions() bool {
	if o != nil && o.InvalidAccessions != nil {
		return true
	}

	return false
}

// SetInvalidAccessions gets a reference to the given []string and assigns it to the InvalidAccessions field.
func (o *V2VirusAvailability) SetInvalidAccessions(v []string) {
	o.InvalidAccessions = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *V2VirusAvailability) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2VirusAvailability) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *V2VirusAvailability) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *V2VirusAvailability) SetMessage(v string) {
	o.Message = &v
}

func (o V2VirusAvailability) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ValidAccessions != nil {
		toSerialize["valid_accessions"] = o.ValidAccessions
	}
	if o.InvalidAccessions != nil {
		toSerialize["invalid_accessions"] = o.InvalidAccessions
	}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableV2VirusAvailability struct {
	value *V2VirusAvailability
	isSet bool
}

func (v NullableV2VirusAvailability) Get() *V2VirusAvailability {
	return v.value
}

func (v *NullableV2VirusAvailability) Set(val *V2VirusAvailability) {
	v.value = val
	v.isSet = true
}

func (v NullableV2VirusAvailability) IsSet() bool {
	return v.isSet
}

func (v *NullableV2VirusAvailability) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2VirusAvailability(val *V2VirusAvailability) *NullableV2VirusAvailability {
	return &NullableV2VirusAvailability{value: val, isSet: true}
}

func (v NullableV2VirusAvailability) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2VirusAvailability) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


