/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncbi-openapi-v2_goland

import (
	"encoding/json"
)

// V2reportsAssemblyDataReportPage struct for V2reportsAssemblyDataReportPage
type V2reportsAssemblyDataReportPage struct {
	Reports []V2reportsAssemblyDataReport `json:"reports,omitempty"`
	ContentType *V2reportsContentType `json:"content_type,omitempty"`
	TotalCount *int32 `json:"total_count,omitempty"`
	NextPageToken *string `json:"next_page_token,omitempty"`
	Messages []V2reportsMessage `json:"messages,omitempty"`
	ReportType *string `json:"_report_type,omitempty"`
	ReportFields []string `json:"_report_fields,omitempty"`
	FirstPage *bool `json:"_first_page,omitempty"`
	ReportFormat *string `json:"_report_format,omitempty"`
}

// NewV2reportsAssemblyDataReportPage instantiates a new V2reportsAssemblyDataReportPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2reportsAssemblyDataReportPage() *V2reportsAssemblyDataReportPage {
	this := V2reportsAssemblyDataReportPage{}
	var contentType V2reportsContentType = V2REPORTSCONTENTTYPE_COMPLETE
	this.ContentType = &contentType
	return &this
}

// NewV2reportsAssemblyDataReportPageWithDefaults instantiates a new V2reportsAssemblyDataReportPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2reportsAssemblyDataReportPageWithDefaults() *V2reportsAssemblyDataReportPage {
	this := V2reportsAssemblyDataReportPage{}
	var contentType V2reportsContentType = V2REPORTSCONTENTTYPE_COMPLETE
	this.ContentType = &contentType
	return &this
}

// GetReports returns the Reports field value if set, zero value otherwise.
func (o *V2reportsAssemblyDataReportPage) GetReports() []V2reportsAssemblyDataReport {
	if o == nil || o.Reports == nil {
		var ret []V2reportsAssemblyDataReport
		return ret
	}
	return o.Reports
}

// GetReportsOk returns a tuple with the Reports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2reportsAssemblyDataReportPage) GetReportsOk() ([]V2reportsAssemblyDataReport, bool) {
	if o == nil || o.Reports == nil {
		return nil, false
	}
	return o.Reports, true
}

// HasReports returns a boolean if a field has been set.
func (o *V2reportsAssemblyDataReportPage) HasReports() bool {
	if o != nil && o.Reports != nil {
		return true
	}

	return false
}

// SetReports gets a reference to the given []V2reportsAssemblyDataReport and assigns it to the Reports field.
func (o *V2reportsAssemblyDataReportPage) SetReports(v []V2reportsAssemblyDataReport) {
	o.Reports = v
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *V2reportsAssemblyDataReportPage) GetContentType() V2reportsContentType {
	if o == nil || o.ContentType == nil {
		var ret V2reportsContentType
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2reportsAssemblyDataReportPage) GetContentTypeOk() (*V2reportsContentType, bool) {
	if o == nil || o.ContentType == nil {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *V2reportsAssemblyDataReportPage) HasContentType() bool {
	if o != nil && o.ContentType != nil {
		return true
	}

	return false
}

// SetContentType gets a reference to the given V2reportsContentType and assigns it to the ContentType field.
func (o *V2reportsAssemblyDataReportPage) SetContentType(v V2reportsContentType) {
	o.ContentType = &v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *V2reportsAssemblyDataReportPage) GetTotalCount() int32 {
	if o == nil || o.TotalCount == nil {
		var ret int32
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2reportsAssemblyDataReportPage) GetTotalCountOk() (*int32, bool) {
	if o == nil || o.TotalCount == nil {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *V2reportsAssemblyDataReportPage) HasTotalCount() bool {
	if o != nil && o.TotalCount != nil {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int32 and assigns it to the TotalCount field.
func (o *V2reportsAssemblyDataReportPage) SetTotalCount(v int32) {
	o.TotalCount = &v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *V2reportsAssemblyDataReportPage) GetNextPageToken() string {
	if o == nil || o.NextPageToken == nil {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2reportsAssemblyDataReportPage) GetNextPageTokenOk() (*string, bool) {
	if o == nil || o.NextPageToken == nil {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *V2reportsAssemblyDataReportPage) HasNextPageToken() bool {
	if o != nil && o.NextPageToken != nil {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *V2reportsAssemblyDataReportPage) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// GetMessages returns the Messages field value if set, zero value otherwise.
func (o *V2reportsAssemblyDataReportPage) GetMessages() []V2reportsMessage {
	if o == nil || o.Messages == nil {
		var ret []V2reportsMessage
		return ret
	}
	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2reportsAssemblyDataReportPage) GetMessagesOk() ([]V2reportsMessage, bool) {
	if o == nil || o.Messages == nil {
		return nil, false
	}
	return o.Messages, true
}

// HasMessages returns a boolean if a field has been set.
func (o *V2reportsAssemblyDataReportPage) HasMessages() bool {
	if o != nil && o.Messages != nil {
		return true
	}

	return false
}

// SetMessages gets a reference to the given []V2reportsMessage and assigns it to the Messages field.
func (o *V2reportsAssemblyDataReportPage) SetMessages(v []V2reportsMessage) {
	o.Messages = v
}

// GetReportType returns the ReportType field value if set, zero value otherwise.
func (o *V2reportsAssemblyDataReportPage) GetReportType() string {
	if o == nil || o.ReportType == nil {
		var ret string
		return ret
	}
	return *o.ReportType
}

// GetReportTypeOk returns a tuple with the ReportType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2reportsAssemblyDataReportPage) GetReportTypeOk() (*string, bool) {
	if o == nil || o.ReportType == nil {
		return nil, false
	}
	return o.ReportType, true
}

// HasReportType returns a boolean if a field has been set.
func (o *V2reportsAssemblyDataReportPage) HasReportType() bool {
	if o != nil && o.ReportType != nil {
		return true
	}

	return false
}

// SetReportType gets a reference to the given string and assigns it to the ReportType field.
func (o *V2reportsAssemblyDataReportPage) SetReportType(v string) {
	o.ReportType = &v
}

// GetReportFields returns the ReportFields field value if set, zero value otherwise.
func (o *V2reportsAssemblyDataReportPage) GetReportFields() []string {
	if o == nil || o.ReportFields == nil {
		var ret []string
		return ret
	}
	return o.ReportFields
}

// GetReportFieldsOk returns a tuple with the ReportFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2reportsAssemblyDataReportPage) GetReportFieldsOk() ([]string, bool) {
	if o == nil || o.ReportFields == nil {
		return nil, false
	}
	return o.ReportFields, true
}

// HasReportFields returns a boolean if a field has been set.
func (o *V2reportsAssemblyDataReportPage) HasReportFields() bool {
	if o != nil && o.ReportFields != nil {
		return true
	}

	return false
}

// SetReportFields gets a reference to the given []string and assigns it to the ReportFields field.
func (o *V2reportsAssemblyDataReportPage) SetReportFields(v []string) {
	o.ReportFields = v
}

// GetFirstPage returns the FirstPage field value if set, zero value otherwise.
func (o *V2reportsAssemblyDataReportPage) GetFirstPage() bool {
	if o == nil || o.FirstPage == nil {
		var ret bool
		return ret
	}
	return *o.FirstPage
}

// GetFirstPageOk returns a tuple with the FirstPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2reportsAssemblyDataReportPage) GetFirstPageOk() (*bool, bool) {
	if o == nil || o.FirstPage == nil {
		return nil, false
	}
	return o.FirstPage, true
}

// HasFirstPage returns a boolean if a field has been set.
func (o *V2reportsAssemblyDataReportPage) HasFirstPage() bool {
	if o != nil && o.FirstPage != nil {
		return true
	}

	return false
}

// SetFirstPage gets a reference to the given bool and assigns it to the FirstPage field.
func (o *V2reportsAssemblyDataReportPage) SetFirstPage(v bool) {
	o.FirstPage = &v
}

// GetReportFormat returns the ReportFormat field value if set, zero value otherwise.
func (o *V2reportsAssemblyDataReportPage) GetReportFormat() string {
	if o == nil || o.ReportFormat == nil {
		var ret string
		return ret
	}
	return *o.ReportFormat
}

// GetReportFormatOk returns a tuple with the ReportFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2reportsAssemblyDataReportPage) GetReportFormatOk() (*string, bool) {
	if o == nil || o.ReportFormat == nil {
		return nil, false
	}
	return o.ReportFormat, true
}

// HasReportFormat returns a boolean if a field has been set.
func (o *V2reportsAssemblyDataReportPage) HasReportFormat() bool {
	if o != nil && o.ReportFormat != nil {
		return true
	}

	return false
}

// SetReportFormat gets a reference to the given string and assigns it to the ReportFormat field.
func (o *V2reportsAssemblyDataReportPage) SetReportFormat(v string) {
	o.ReportFormat = &v
}

func (o V2reportsAssemblyDataReportPage) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Reports != nil {
		toSerialize["reports"] = o.Reports
	}
	if o.ContentType != nil {
		toSerialize["content_type"] = o.ContentType
	}
	if o.TotalCount != nil {
		toSerialize["total_count"] = o.TotalCount
	}
	if o.NextPageToken != nil {
		toSerialize["next_page_token"] = o.NextPageToken
	}
	if o.Messages != nil {
		toSerialize["messages"] = o.Messages
	}
	if o.ReportType != nil {
		toSerialize["_report_type"] = o.ReportType
	}
	if o.ReportFields != nil {
		toSerialize["_report_fields"] = o.ReportFields
	}
	if o.FirstPage != nil {
		toSerialize["_first_page"] = o.FirstPage
	}
	if o.ReportFormat != nil {
		toSerialize["_report_format"] = o.ReportFormat
	}
	return json.Marshal(toSerialize)
}

type NullableV2reportsAssemblyDataReportPage struct {
	value *V2reportsAssemblyDataReportPage
	isSet bool
}

func (v NullableV2reportsAssemblyDataReportPage) Get() *V2reportsAssemblyDataReportPage {
	return v.value
}

func (v *NullableV2reportsAssemblyDataReportPage) Set(val *V2reportsAssemblyDataReportPage) {
	v.value = val
	v.isSet = true
}

func (v NullableV2reportsAssemblyDataReportPage) IsSet() bool {
	return v.isSet
}

func (v *NullableV2reportsAssemblyDataReportPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2reportsAssemblyDataReportPage(val *V2reportsAssemblyDataReportPage) *NullableV2reportsAssemblyDataReportPage {
	return &NullableV2reportsAssemblyDataReportPage{value: val, isSet: true}
}

func (v NullableV2reportsAssemblyDataReportPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2reportsAssemblyDataReportPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


