/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncbi-openapi-v2_goland

import (
	"encoding/json"
)

// V2GeneChromosomeSummaryReplyGeneChromosomeSummary struct for V2GeneChromosomeSummaryReplyGeneChromosomeSummary
type V2GeneChromosomeSummaryReplyGeneChromosomeSummary struct {
	Name *string `json:"name,omitempty"`
	Count *int32 `json:"count,omitempty"`
	Accession *string `json:"accession,omitempty"`
}

// NewV2GeneChromosomeSummaryReplyGeneChromosomeSummary instantiates a new V2GeneChromosomeSummaryReplyGeneChromosomeSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2GeneChromosomeSummaryReplyGeneChromosomeSummary() *V2GeneChromosomeSummaryReplyGeneChromosomeSummary {
	this := V2GeneChromosomeSummaryReplyGeneChromosomeSummary{}
	return &this
}

// NewV2GeneChromosomeSummaryReplyGeneChromosomeSummaryWithDefaults instantiates a new V2GeneChromosomeSummaryReplyGeneChromosomeSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2GeneChromosomeSummaryReplyGeneChromosomeSummaryWithDefaults() *V2GeneChromosomeSummaryReplyGeneChromosomeSummary {
	this := V2GeneChromosomeSummaryReplyGeneChromosomeSummary{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V2GeneChromosomeSummaryReplyGeneChromosomeSummary) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2GeneChromosomeSummaryReplyGeneChromosomeSummary) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V2GeneChromosomeSummaryReplyGeneChromosomeSummary) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V2GeneChromosomeSummaryReplyGeneChromosomeSummary) SetName(v string) {
	o.Name = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *V2GeneChromosomeSummaryReplyGeneChromosomeSummary) GetCount() int32 {
	if o == nil || o.Count == nil {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2GeneChromosomeSummaryReplyGeneChromosomeSummary) GetCountOk() (*int32, bool) {
	if o == nil || o.Count == nil {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *V2GeneChromosomeSummaryReplyGeneChromosomeSummary) HasCount() bool {
	if o != nil && o.Count != nil {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *V2GeneChromosomeSummaryReplyGeneChromosomeSummary) SetCount(v int32) {
	o.Count = &v
}

// GetAccession returns the Accession field value if set, zero value otherwise.
func (o *V2GeneChromosomeSummaryReplyGeneChromosomeSummary) GetAccession() string {
	if o == nil || o.Accession == nil {
		var ret string
		return ret
	}
	return *o.Accession
}

// GetAccessionOk returns a tuple with the Accession field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2GeneChromosomeSummaryReplyGeneChromosomeSummary) GetAccessionOk() (*string, bool) {
	if o == nil || o.Accession == nil {
		return nil, false
	}
	return o.Accession, true
}

// HasAccession returns a boolean if a field has been set.
func (o *V2GeneChromosomeSummaryReplyGeneChromosomeSummary) HasAccession() bool {
	if o != nil && o.Accession != nil {
		return true
	}

	return false
}

// SetAccession gets a reference to the given string and assigns it to the Accession field.
func (o *V2GeneChromosomeSummaryReplyGeneChromosomeSummary) SetAccession(v string) {
	o.Accession = &v
}

func (o V2GeneChromosomeSummaryReplyGeneChromosomeSummary) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Count != nil {
		toSerialize["count"] = o.Count
	}
	if o.Accession != nil {
		toSerialize["accession"] = o.Accession
	}
	return json.Marshal(toSerialize)
}

type NullableV2GeneChromosomeSummaryReplyGeneChromosomeSummary struct {
	value *V2GeneChromosomeSummaryReplyGeneChromosomeSummary
	isSet bool
}

func (v NullableV2GeneChromosomeSummaryReplyGeneChromosomeSummary) Get() *V2GeneChromosomeSummaryReplyGeneChromosomeSummary {
	return v.value
}

func (v *NullableV2GeneChromosomeSummaryReplyGeneChromosomeSummary) Set(val *V2GeneChromosomeSummaryReplyGeneChromosomeSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableV2GeneChromosomeSummaryReplyGeneChromosomeSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableV2GeneChromosomeSummaryReplyGeneChromosomeSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2GeneChromosomeSummaryReplyGeneChromosomeSummary(val *V2GeneChromosomeSummaryReplyGeneChromosomeSummary) *NullableV2GeneChromosomeSummaryReplyGeneChromosomeSummary {
	return &NullableV2GeneChromosomeSummaryReplyGeneChromosomeSummary{value: val, isSet: true}
}

func (v NullableV2GeneChromosomeSummaryReplyGeneChromosomeSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2GeneChromosomeSummaryReplyGeneChromosomeSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


