/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// V2reportsErrorOrganelleErrorCode the model 'V2reportsErrorOrganelleErrorCode'
type V2reportsErrorOrganelleErrorCode string

// List of v2reportsErrorOrganelleErrorCode
const (
	V2REPORTSERRORORGANELLEERRORCODE_UNKNOWN_ORGANELLE_ERROR_CODE V2reportsErrorOrganelleErrorCode = "UNKNOWN_ORGANELLE_ERROR_CODE"
	V2REPORTSERRORORGANELLEERRORCODE_INVALID_ORGANELLE_TAXON V2reportsErrorOrganelleErrorCode = "INVALID_ORGANELLE_TAXON"
	V2REPORTSERRORORGANELLEERRORCODE_NO_ORGANELLES_FOR_ACCESSION V2reportsErrorOrganelleErrorCode = "NO_ORGANELLES_FOR_ACCESSION"
)

// All allowed values of V2reportsErrorOrganelleErrorCode enum
var AllowedV2reportsErrorOrganelleErrorCodeEnumValues = []V2reportsErrorOrganelleErrorCode{
	"UNKNOWN_ORGANELLE_ERROR_CODE",
	"INVALID_ORGANELLE_TAXON",
	"NO_ORGANELLES_FOR_ACCESSION",
}

func (v *V2reportsErrorOrganelleErrorCode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V2reportsErrorOrganelleErrorCode(value)
	for _, existing := range AllowedV2reportsErrorOrganelleErrorCodeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V2reportsErrorOrganelleErrorCode", value)
}

// NewV2reportsErrorOrganelleErrorCodeFromValue returns a pointer to a valid V2reportsErrorOrganelleErrorCode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV2reportsErrorOrganelleErrorCodeFromValue(v string) (*V2reportsErrorOrganelleErrorCode, error) {
	ev := V2reportsErrorOrganelleErrorCode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V2reportsErrorOrganelleErrorCode: valid values are %v", v, AllowedV2reportsErrorOrganelleErrorCodeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V2reportsErrorOrganelleErrorCode) IsValid() bool {
	for _, existing := range AllowedV2reportsErrorOrganelleErrorCodeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v2reportsErrorOrganelleErrorCode value
func (v V2reportsErrorOrganelleErrorCode) Ptr() *V2reportsErrorOrganelleErrorCode {
	return &v
}

type NullableV2reportsErrorOrganelleErrorCode struct {
	value *V2reportsErrorOrganelleErrorCode
	isSet bool
}

func (v NullableV2reportsErrorOrganelleErrorCode) Get() *V2reportsErrorOrganelleErrorCode {
	return v.value
}

func (v *NullableV2reportsErrorOrganelleErrorCode) Set(val *V2reportsErrorOrganelleErrorCode) {
	v.value = val
	v.isSet = true
}

func (v NullableV2reportsErrorOrganelleErrorCode) IsSet() bool {
	return v.isSet
}

func (v *NullableV2reportsErrorOrganelleErrorCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2reportsErrorOrganelleErrorCode(val *V2reportsErrorOrganelleErrorCode) *NullableV2reportsErrorOrganelleErrorCode {
	return &NullableV2reportsErrorOrganelleErrorCode{value: val, isSet: true}
}

func (v NullableV2reportsErrorOrganelleErrorCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2reportsErrorOrganelleErrorCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

