/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncbi-openapi-v2_goland

import (
	"encoding/json"
	"fmt"
)

// V2reportsVirusAssemblyCompleteness the model 'V2reportsVirusAssemblyCompleteness'
type V2reportsVirusAssemblyCompleteness string

// List of v2reportsVirusAssemblyCompleteness
const (
	V2REPORTSVIRUSASSEMBLYCOMPLETENESS_UNKNOWN V2reportsVirusAssemblyCompleteness = "UNKNOWN"
	V2REPORTSVIRUSASSEMBLYCOMPLETENESS_COMPLETE V2reportsVirusAssemblyCompleteness = "COMPLETE"
	V2REPORTSVIRUSASSEMBLYCOMPLETENESS_PARTIAL V2reportsVirusAssemblyCompleteness = "PARTIAL"
)

// All allowed values of V2reportsVirusAssemblyCompleteness enum
var AllowedV2reportsVirusAssemblyCompletenessEnumValues = []V2reportsVirusAssemblyCompleteness{
	"UNKNOWN",
	"COMPLETE",
	"PARTIAL",
}

func (v *V2reportsVirusAssemblyCompleteness) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V2reportsVirusAssemblyCompleteness(value)
	for _, existing := range AllowedV2reportsVirusAssemblyCompletenessEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V2reportsVirusAssemblyCompleteness", value)
}

// NewV2reportsVirusAssemblyCompletenessFromValue returns a pointer to a valid V2reportsVirusAssemblyCompleteness
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV2reportsVirusAssemblyCompletenessFromValue(v string) (*V2reportsVirusAssemblyCompleteness, error) {
	ev := V2reportsVirusAssemblyCompleteness(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V2reportsVirusAssemblyCompleteness: valid values are %v", v, AllowedV2reportsVirusAssemblyCompletenessEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V2reportsVirusAssemblyCompleteness) IsValid() bool {
	for _, existing := range AllowedV2reportsVirusAssemblyCompletenessEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v2reportsVirusAssemblyCompleteness value
func (v V2reportsVirusAssemblyCompleteness) Ptr() *V2reportsVirusAssemblyCompleteness {
	return &v
}

type NullableV2reportsVirusAssemblyCompleteness struct {
	value *V2reportsVirusAssemblyCompleteness
	isSet bool
}

func (v NullableV2reportsVirusAssemblyCompleteness) Get() *V2reportsVirusAssemblyCompleteness {
	return v.value
}

func (v *NullableV2reportsVirusAssemblyCompleteness) Set(val *V2reportsVirusAssemblyCompleteness) {
	v.value = val
	v.isSet = true
}

func (v NullableV2reportsVirusAssemblyCompleteness) IsSet() bool {
	return v.isSet
}

func (v *NullableV2reportsVirusAssemblyCompleteness) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2reportsVirusAssemblyCompleteness(val *V2reportsVirusAssemblyCompleteness) *NullableV2reportsVirusAssemblyCompleteness {
	return &NullableV2reportsVirusAssemblyCompleteness{value: val, isSet: true}
}

func (v NullableV2reportsVirusAssemblyCompleteness) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2reportsVirusAssemblyCompleteness) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

