/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncbi-openapi-v2_goland

import (
	"encoding/json"
	"fmt"
)

// V2reportsRnaType the model 'V2reportsRnaType'
type V2reportsRnaType string

// List of v2reportsRnaType
const (
	V2REPORTSRNATYPE_RNA_UNKNOWN V2reportsRnaType = "rna_UNKNOWN"
	V2REPORTSRNATYPE_PREMSG V2reportsRnaType = "premsg"
	V2REPORTSRNATYPE_TM_RNA V2reportsRnaType = "tmRna"
)

// All allowed values of V2reportsRnaType enum
var AllowedV2reportsRnaTypeEnumValues = []V2reportsRnaType{
	"rna_UNKNOWN",
	"premsg",
	"tmRna",
}

func (v *V2reportsRnaType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V2reportsRnaType(value)
	for _, existing := range AllowedV2reportsRnaTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V2reportsRnaType", value)
}

// NewV2reportsRnaTypeFromValue returns a pointer to a valid V2reportsRnaType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV2reportsRnaTypeFromValue(v string) (*V2reportsRnaType, error) {
	ev := V2reportsRnaType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V2reportsRnaType: valid values are %v", v, AllowedV2reportsRnaTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V2reportsRnaType) IsValid() bool {
	for _, existing := range AllowedV2reportsRnaTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v2reportsRnaType value
func (v V2reportsRnaType) Ptr() *V2reportsRnaType {
	return &v
}

type NullableV2reportsRnaType struct {
	value *V2reportsRnaType
	isSet bool
}

func (v NullableV2reportsRnaType) Get() *V2reportsRnaType {
	return v.value
}

func (v *NullableV2reportsRnaType) Set(val *V2reportsRnaType) {
	v.value = val
	v.isSet = true
}

func (v NullableV2reportsRnaType) IsSet() bool {
	return v.isSet
}

func (v *NullableV2reportsRnaType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2reportsRnaType(val *V2reportsRnaType) *NullableV2reportsRnaType {
	return &NullableV2reportsRnaType{value: val, isSet: true}
}

func (v NullableV2reportsRnaType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2reportsRnaType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

