/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncbi-openapi-v2_goland

import (
	"encoding/json"
	"fmt"
)

// V2reportsOrientation the model 'V2reportsOrientation'
type V2reportsOrientation string

// List of v2reportsOrientation
const (
	V2REPORTSORIENTATION_NONE V2reportsOrientation = "none"
	V2REPORTSORIENTATION_PLUS V2reportsOrientation = "plus"
	V2REPORTSORIENTATION_MINUS V2reportsOrientation = "minus"
)

// All allowed values of V2reportsOrientation enum
var AllowedV2reportsOrientationEnumValues = []V2reportsOrientation{
	"none",
	"plus",
	"minus",
}

func (v *V2reportsOrientation) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V2reportsOrientation(value)
	for _, existing := range AllowedV2reportsOrientationEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V2reportsOrientation", value)
}

// NewV2reportsOrientationFromValue returns a pointer to a valid V2reportsOrientation
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV2reportsOrientationFromValue(v string) (*V2reportsOrientation, error) {
	ev := V2reportsOrientation(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V2reportsOrientation: valid values are %v", v, AllowedV2reportsOrientationEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V2reportsOrientation) IsValid() bool {
	for _, existing := range AllowedV2reportsOrientationEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v2reportsOrientation value
func (v V2reportsOrientation) Ptr() *V2reportsOrientation {
	return &v
}

type NullableV2reportsOrientation struct {
	value *V2reportsOrientation
	isSet bool
}

func (v NullableV2reportsOrientation) Get() *V2reportsOrientation {
	return v.value
}

func (v *NullableV2reportsOrientation) Set(val *V2reportsOrientation) {
	v.value = val
	v.isSet = true
}

func (v NullableV2reportsOrientation) IsSet() bool {
	return v.isSet
}

func (v *NullableV2reportsOrientation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2reportsOrientation(val *V2reportsOrientation) *NullableV2reportsOrientation {
	return &NullableV2reportsOrientation{value: val, isSet: true}
}

func (v NullableV2reportsOrientation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2reportsOrientation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

