/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V2AssemblyLinksRequest struct for V2AssemblyLinksRequest
type V2AssemblyLinksRequest struct {
	Accessions []string `json:"accessions,omitempty"`
}

// NewV2AssemblyLinksRequest instantiates a new V2AssemblyLinksRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2AssemblyLinksRequest() *V2AssemblyLinksRequest {
	this := V2AssemblyLinksRequest{}
	return &this
}

// NewV2AssemblyLinksRequestWithDefaults instantiates a new V2AssemblyLinksRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2AssemblyLinksRequestWithDefaults() *V2AssemblyLinksRequest {
	this := V2AssemblyLinksRequest{}
	return &this
}

// GetAccessions returns the Accessions field value if set, zero value otherwise.
func (o *V2AssemblyLinksRequest) GetAccessions() []string {
	if o == nil || o.Accessions == nil {
		var ret []string
		return ret
	}
	return o.Accessions
}

// GetAccessionsOk returns a tuple with the Accessions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssemblyLinksRequest) GetAccessionsOk() ([]string, bool) {
	if o == nil || o.Accessions == nil {
		return nil, false
	}
	return o.Accessions, true
}

// HasAccessions returns a boolean if a field has been set.
func (o *V2AssemblyLinksRequest) HasAccessions() bool {
	if o != nil && o.Accessions != nil {
		return true
	}

	return false
}

// SetAccessions gets a reference to the given []string and assigns it to the Accessions field.
func (o *V2AssemblyLinksRequest) SetAccessions(v []string) {
	o.Accessions = v
}

func (o V2AssemblyLinksRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Accessions != nil {
		toSerialize["accessions"] = o.Accessions
	}
	return json.Marshal(toSerialize)
}

type NullableV2AssemblyLinksRequest struct {
	value *V2AssemblyLinksRequest
	isSet bool
}

func (v NullableV2AssemblyLinksRequest) Get() *V2AssemblyLinksRequest {
	return v.value
}

func (v *NullableV2AssemblyLinksRequest) Set(val *V2AssemblyLinksRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV2AssemblyLinksRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV2AssemblyLinksRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2AssemblyLinksRequest(val *V2AssemblyLinksRequest) *NullableV2AssemblyLinksRequest {
	return &NullableV2AssemblyLinksRequest{value: val, isSet: true}
}

func (v NullableV2AssemblyLinksRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2AssemblyLinksRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


