/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncbi-openapi-v2_goland

import (
	"encoding/json"
)

// V2reportsRange struct for V2reportsRange
type V2reportsRange struct {
	Begin *string `json:"begin,omitempty"`
	End *string `json:"end,omitempty"`
	Orientation *V2reportsOrientation `json:"orientation,omitempty"`
	Order *int32 `json:"order,omitempty"`
	RibosomalSlippage *int32 `json:"ribosomal_slippage,omitempty"`
}

// NewV2reportsRange instantiates a new V2reportsRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2reportsRange() *V2reportsRange {
	this := V2reportsRange{}
	var orientation V2reportsOrientation = V2REPORTSORIENTATION_NONE
	this.Orientation = &orientation
	return &this
}

// NewV2reportsRangeWithDefaults instantiates a new V2reportsRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2reportsRangeWithDefaults() *V2reportsRange {
	this := V2reportsRange{}
	var orientation V2reportsOrientation = V2REPORTSORIENTATION_NONE
	this.Orientation = &orientation
	return &this
}

// GetBegin returns the Begin field value if set, zero value otherwise.
func (o *V2reportsRange) GetBegin() string {
	if o == nil || o.Begin == nil {
		var ret string
		return ret
	}
	return *o.Begin
}

// GetBeginOk returns a tuple with the Begin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2reportsRange) GetBeginOk() (*string, bool) {
	if o == nil || o.Begin == nil {
		return nil, false
	}
	return o.Begin, true
}

// HasBegin returns a boolean if a field has been set.
func (o *V2reportsRange) HasBegin() bool {
	if o != nil && o.Begin != nil {
		return true
	}

	return false
}

// SetBegin gets a reference to the given string and assigns it to the Begin field.
func (o *V2reportsRange) SetBegin(v string) {
	o.Begin = &v
}

// GetEnd returns the End field value if set, zero value otherwise.
func (o *V2reportsRange) GetEnd() string {
	if o == nil || o.End == nil {
		var ret string
		return ret
	}
	return *o.End
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2reportsRange) GetEndOk() (*string, bool) {
	if o == nil || o.End == nil {
		return nil, false
	}
	return o.End, true
}

// HasEnd returns a boolean if a field has been set.
func (o *V2reportsRange) HasEnd() bool {
	if o != nil && o.End != nil {
		return true
	}

	return false
}

// SetEnd gets a reference to the given string and assigns it to the End field.
func (o *V2reportsRange) SetEnd(v string) {
	o.End = &v
}

// GetOrientation returns the Orientation field value if set, zero value otherwise.
func (o *V2reportsRange) GetOrientation() V2reportsOrientation {
	if o == nil || o.Orientation == nil {
		var ret V2reportsOrientation
		return ret
	}
	return *o.Orientation
}

// GetOrientationOk returns a tuple with the Orientation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2reportsRange) GetOrientationOk() (*V2reportsOrientation, bool) {
	if o == nil || o.Orientation == nil {
		return nil, false
	}
	return o.Orientation, true
}

// HasOrientation returns a boolean if a field has been set.
func (o *V2reportsRange) HasOrientation() bool {
	if o != nil && o.Orientation != nil {
		return true
	}

	return false
}

// SetOrientation gets a reference to the given V2reportsOrientation and assigns it to the Orientation field.
func (o *V2reportsRange) SetOrientation(v V2reportsOrientation) {
	o.Orientation = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *V2reportsRange) GetOrder() int32 {
	if o == nil || o.Order == nil {
		var ret int32
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2reportsRange) GetOrderOk() (*int32, bool) {
	if o == nil || o.Order == nil {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *V2reportsRange) HasOrder() bool {
	if o != nil && o.Order != nil {
		return true
	}

	return false
}

// SetOrder gets a reference to the given int32 and assigns it to the Order field.
func (o *V2reportsRange) SetOrder(v int32) {
	o.Order = &v
}

// GetRibosomalSlippage returns the RibosomalSlippage field value if set, zero value otherwise.
func (o *V2reportsRange) GetRibosomalSlippage() int32 {
	if o == nil || o.RibosomalSlippage == nil {
		var ret int32
		return ret
	}
	return *o.RibosomalSlippage
}

// GetRibosomalSlippageOk returns a tuple with the RibosomalSlippage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2reportsRange) GetRibosomalSlippageOk() (*int32, bool) {
	if o == nil || o.RibosomalSlippage == nil {
		return nil, false
	}
	return o.RibosomalSlippage, true
}

// HasRibosomalSlippage returns a boolean if a field has been set.
func (o *V2reportsRange) HasRibosomalSlippage() bool {
	if o != nil && o.RibosomalSlippage != nil {
		return true
	}

	return false
}

// SetRibosomalSlippage gets a reference to the given int32 and assigns it to the RibosomalSlippage field.
func (o *V2reportsRange) SetRibosomalSlippage(v int32) {
	o.RibosomalSlippage = &v
}

func (o V2reportsRange) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Begin != nil {
		toSerialize["begin"] = o.Begin
	}
	if o.End != nil {
		toSerialize["end"] = o.End
	}
	if o.Orientation != nil {
		toSerialize["orientation"] = o.Orientation
	}
	if o.Order != nil {
		toSerialize["order"] = o.Order
	}
	if o.RibosomalSlippage != nil {
		toSerialize["ribosomal_slippage"] = o.RibosomalSlippage
	}
	return json.Marshal(toSerialize)
}

type NullableV2reportsRange struct {
	value *V2reportsRange
	isSet bool
}

func (v NullableV2reportsRange) Get() *V2reportsRange {
	return v.value
}

func (v *NullableV2reportsRange) Set(val *V2reportsRange) {
	v.value = val
	v.isSet = true
}

func (v NullableV2reportsRange) IsSet() bool {
	return v.isSet
}

func (v *NullableV2reportsRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2reportsRange(val *V2reportsRange) *NullableV2reportsRange {
	return &NullableV2reportsRange{value: val, isSet: true}
}

func (v NullableV2reportsRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2reportsRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


