/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// V2GeneLinksReplyGeneLinkType the model 'V2GeneLinksReplyGeneLinkType'
type V2GeneLinksReplyGeneLinkType string

// List of v2GeneLinksReplyGeneLinkType
const (
	V2GENELINKSREPLYGENELINKTYPE_GENE_LINK V2GeneLinksReplyGeneLinkType = "GENE_LINK"
	V2GENELINKSREPLYGENELINKTYPE_GDV_LINK V2GeneLinksReplyGeneLinkType = "GDV_LINK"
	V2GENELINKSREPLYGENELINKTYPE_ORTHOLOG_LINK V2GeneLinksReplyGeneLinkType = "ORTHOLOG_LINK"
)

// All allowed values of V2GeneLinksReplyGeneLinkType enum
var AllowedV2GeneLinksReplyGeneLinkTypeEnumValues = []V2GeneLinksReplyGeneLinkType{
	"GENE_LINK",
	"GDV_LINK",
	"ORTHOLOG_LINK",
}

func (v *V2GeneLinksReplyGeneLinkType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V2GeneLinksReplyGeneLinkType(value)
	for _, existing := range AllowedV2GeneLinksReplyGeneLinkTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V2GeneLinksReplyGeneLinkType", value)
}

// NewV2GeneLinksReplyGeneLinkTypeFromValue returns a pointer to a valid V2GeneLinksReplyGeneLinkType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV2GeneLinksReplyGeneLinkTypeFromValue(v string) (*V2GeneLinksReplyGeneLinkType, error) {
	ev := V2GeneLinksReplyGeneLinkType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V2GeneLinksReplyGeneLinkType: valid values are %v", v, AllowedV2GeneLinksReplyGeneLinkTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V2GeneLinksReplyGeneLinkType) IsValid() bool {
	for _, existing := range AllowedV2GeneLinksReplyGeneLinkTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v2GeneLinksReplyGeneLinkType value
func (v V2GeneLinksReplyGeneLinkType) Ptr() *V2GeneLinksReplyGeneLinkType {
	return &v
}

type NullableV2GeneLinksReplyGeneLinkType struct {
	value *V2GeneLinksReplyGeneLinkType
	isSet bool
}

func (v NullableV2GeneLinksReplyGeneLinkType) Get() *V2GeneLinksReplyGeneLinkType {
	return v.value
}

func (v *NullableV2GeneLinksReplyGeneLinkType) Set(val *V2GeneLinksReplyGeneLinkType) {
	v.value = val
	v.isSet = true
}

func (v NullableV2GeneLinksReplyGeneLinkType) IsSet() bool {
	return v.isSet
}

func (v *NullableV2GeneLinksReplyGeneLinkType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2GeneLinksReplyGeneLinkType(val *V2GeneLinksReplyGeneLinkType) *NullableV2GeneLinksReplyGeneLinkType {
	return &NullableV2GeneLinksReplyGeneLinkType{value: val, isSet: true}
}

func (v NullableV2GeneLinksReplyGeneLinkType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2GeneLinksReplyGeneLinkType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

