/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// V2GenomeAnnotationRequestGenomeAnnotationTableFormat the model 'V2GenomeAnnotationRequestGenomeAnnotationTableFormat'
type V2GenomeAnnotationRequestGenomeAnnotationTableFormat string

// List of v2GenomeAnnotationRequestGenomeAnnotationTableFormat
const (
	V2GENOMEANNOTATIONREQUESTGENOMEANNOTATIONTABLEFORMAT_NO_TABLE V2GenomeAnnotationRequestGenomeAnnotationTableFormat = "NO_TABLE"
	V2GENOMEANNOTATIONREQUESTGENOMEANNOTATIONTABLEFORMAT_SUMMARY V2GenomeAnnotationRequestGenomeAnnotationTableFormat = "SUMMARY"
	V2GENOMEANNOTATIONREQUESTGENOMEANNOTATIONTABLEFORMAT_PRODUCT V2GenomeAnnotationRequestGenomeAnnotationTableFormat = "PRODUCT"
)

// All allowed values of V2GenomeAnnotationRequestGenomeAnnotationTableFormat enum
var AllowedV2GenomeAnnotationRequestGenomeAnnotationTableFormatEnumValues = []V2GenomeAnnotationRequestGenomeAnnotationTableFormat{
	"NO_TABLE",
	"SUMMARY",
	"PRODUCT",
}

func (v *V2GenomeAnnotationRequestGenomeAnnotationTableFormat) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V2GenomeAnnotationRequestGenomeAnnotationTableFormat(value)
	for _, existing := range AllowedV2GenomeAnnotationRequestGenomeAnnotationTableFormatEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V2GenomeAnnotationRequestGenomeAnnotationTableFormat", value)
}

// NewV2GenomeAnnotationRequestGenomeAnnotationTableFormatFromValue returns a pointer to a valid V2GenomeAnnotationRequestGenomeAnnotationTableFormat
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV2GenomeAnnotationRequestGenomeAnnotationTableFormatFromValue(v string) (*V2GenomeAnnotationRequestGenomeAnnotationTableFormat, error) {
	ev := V2GenomeAnnotationRequestGenomeAnnotationTableFormat(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V2GenomeAnnotationRequestGenomeAnnotationTableFormat: valid values are %v", v, AllowedV2GenomeAnnotationRequestGenomeAnnotationTableFormatEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V2GenomeAnnotationRequestGenomeAnnotationTableFormat) IsValid() bool {
	for _, existing := range AllowedV2GenomeAnnotationRequestGenomeAnnotationTableFormatEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v2GenomeAnnotationRequestGenomeAnnotationTableFormat value
func (v V2GenomeAnnotationRequestGenomeAnnotationTableFormat) Ptr() *V2GenomeAnnotationRequestGenomeAnnotationTableFormat {
	return &v
}

type NullableV2GenomeAnnotationRequestGenomeAnnotationTableFormat struct {
	value *V2GenomeAnnotationRequestGenomeAnnotationTableFormat
	isSet bool
}

func (v NullableV2GenomeAnnotationRequestGenomeAnnotationTableFormat) Get() *V2GenomeAnnotationRequestGenomeAnnotationTableFormat {
	return v.value
}

func (v *NullableV2GenomeAnnotationRequestGenomeAnnotationTableFormat) Set(val *V2GenomeAnnotationRequestGenomeAnnotationTableFormat) {
	v.value = val
	v.isSet = true
}

func (v NullableV2GenomeAnnotationRequestGenomeAnnotationTableFormat) IsSet() bool {
	return v.isSet
}

func (v *NullableV2GenomeAnnotationRequestGenomeAnnotationTableFormat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2GenomeAnnotationRequestGenomeAnnotationTableFormat(val *V2GenomeAnnotationRequestGenomeAnnotationTableFormat) *NullableV2GenomeAnnotationRequestGenomeAnnotationTableFormat {
	return &NullableV2GenomeAnnotationRequestGenomeAnnotationTableFormat{value: val, isSet: true}
}

func (v NullableV2GenomeAnnotationRequestGenomeAnnotationTableFormat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2GenomeAnnotationRequestGenomeAnnotationTableFormat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

