/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncbi-openapi-v2_goland

import (
	"encoding/json"
	"fmt"
)

// V2reportsVirusPeptideViralPeptideCompleteness the model 'V2reportsVirusPeptideViralPeptideCompleteness'
type V2reportsVirusPeptideViralPeptideCompleteness string

// List of v2reportsVirusPeptideViralPeptideCompleteness
const (
	V2REPORTSVIRUSPEPTIDEVIRALPEPTIDECOMPLETENESS_UNKNOWN V2reportsVirusPeptideViralPeptideCompleteness = "UNKNOWN"
	V2REPORTSVIRUSPEPTIDEVIRALPEPTIDECOMPLETENESS_COMPLETE V2reportsVirusPeptideViralPeptideCompleteness = "COMPLETE"
	V2REPORTSVIRUSPEPTIDEVIRALPEPTIDECOMPLETENESS_PARTIAL V2reportsVirusPeptideViralPeptideCompleteness = "PARTIAL"
)

// All allowed values of V2reportsVirusPeptideViralPeptideCompleteness enum
var AllowedV2reportsVirusPeptideViralPeptideCompletenessEnumValues = []V2reportsVirusPeptideViralPeptideCompleteness{
	"UNKNOWN",
	"COMPLETE",
	"PARTIAL",
}

func (v *V2reportsVirusPeptideViralPeptideCompleteness) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V2reportsVirusPeptideViralPeptideCompleteness(value)
	for _, existing := range AllowedV2reportsVirusPeptideViralPeptideCompletenessEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V2reportsVirusPeptideViralPeptideCompleteness", value)
}

// NewV2reportsVirusPeptideViralPeptideCompletenessFromValue returns a pointer to a valid V2reportsVirusPeptideViralPeptideCompleteness
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV2reportsVirusPeptideViralPeptideCompletenessFromValue(v string) (*V2reportsVirusPeptideViralPeptideCompleteness, error) {
	ev := V2reportsVirusPeptideViralPeptideCompleteness(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V2reportsVirusPeptideViralPeptideCompleteness: valid values are %v", v, AllowedV2reportsVirusPeptideViralPeptideCompletenessEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V2reportsVirusPeptideViralPeptideCompleteness) IsValid() bool {
	for _, existing := range AllowedV2reportsVirusPeptideViralPeptideCompletenessEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v2reportsVirusPeptideViralPeptideCompleteness value
func (v V2reportsVirusPeptideViralPeptideCompleteness) Ptr() *V2reportsVirusPeptideViralPeptideCompleteness {
	return &v
}

type NullableV2reportsVirusPeptideViralPeptideCompleteness struct {
	value *V2reportsVirusPeptideViralPeptideCompleteness
	isSet bool
}

func (v NullableV2reportsVirusPeptideViralPeptideCompleteness) Get() *V2reportsVirusPeptideViralPeptideCompleteness {
	return v.value
}

func (v *NullableV2reportsVirusPeptideViralPeptideCompleteness) Set(val *V2reportsVirusPeptideViralPeptideCompleteness) {
	v.value = val
	v.isSet = true
}

func (v NullableV2reportsVirusPeptideViralPeptideCompleteness) IsSet() bool {
	return v.isSet
}

func (v *NullableV2reportsVirusPeptideViralPeptideCompleteness) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2reportsVirusPeptideViralPeptideCompleteness(val *V2reportsVirusPeptideViralPeptideCompleteness) *NullableV2reportsVirusPeptideViralPeptideCompleteness {
	return &NullableV2reportsVirusPeptideViralPeptideCompleteness{value: val, isSet: true}
}

func (v NullableV2reportsVirusPeptideViralPeptideCompleteness) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2reportsVirusPeptideViralPeptideCompleteness) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

