/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V2TaxonomyImageMetadataResponse struct for V2TaxonomyImageMetadataResponse
type V2TaxonomyImageMetadataResponse struct {
	TaxId *string `json:"tax_id,omitempty"`
	Src *string `json:"src,omitempty"`
	License *string `json:"license,omitempty"`
	Attribution *string `json:"attribution,omitempty"`
	Source *string `json:"source,omitempty"`
	ImageSizes []V2ImageSize `json:"image_sizes,omitempty"`
	Format *string `json:"format,omitempty"`
}

// NewV2TaxonomyImageMetadataResponse instantiates a new V2TaxonomyImageMetadataResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2TaxonomyImageMetadataResponse() *V2TaxonomyImageMetadataResponse {
	this := V2TaxonomyImageMetadataResponse{}
	return &this
}

// NewV2TaxonomyImageMetadataResponseWithDefaults instantiates a new V2TaxonomyImageMetadataResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2TaxonomyImageMetadataResponseWithDefaults() *V2TaxonomyImageMetadataResponse {
	this := V2TaxonomyImageMetadataResponse{}
	return &this
}

// GetTaxId returns the TaxId field value if set, zero value otherwise.
func (o *V2TaxonomyImageMetadataResponse) GetTaxId() string {
	if o == nil || o.TaxId == nil {
		var ret string
		return ret
	}
	return *o.TaxId
}

// GetTaxIdOk returns a tuple with the TaxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2TaxonomyImageMetadataResponse) GetTaxIdOk() (*string, bool) {
	if o == nil || o.TaxId == nil {
		return nil, false
	}
	return o.TaxId, true
}

// HasTaxId returns a boolean if a field has been set.
func (o *V2TaxonomyImageMetadataResponse) HasTaxId() bool {
	if o != nil && o.TaxId != nil {
		return true
	}

	return false
}

// SetTaxId gets a reference to the given string and assigns it to the TaxId field.
func (o *V2TaxonomyImageMetadataResponse) SetTaxId(v string) {
	o.TaxId = &v
}

// GetSrc returns the Src field value if set, zero value otherwise.
func (o *V2TaxonomyImageMetadataResponse) GetSrc() string {
	if o == nil || o.Src == nil {
		var ret string
		return ret
	}
	return *o.Src
}

// GetSrcOk returns a tuple with the Src field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2TaxonomyImageMetadataResponse) GetSrcOk() (*string, bool) {
	if o == nil || o.Src == nil {
		return nil, false
	}
	return o.Src, true
}

// HasSrc returns a boolean if a field has been set.
func (o *V2TaxonomyImageMetadataResponse) HasSrc() bool {
	if o != nil && o.Src != nil {
		return true
	}

	return false
}

// SetSrc gets a reference to the given string and assigns it to the Src field.
func (o *V2TaxonomyImageMetadataResponse) SetSrc(v string) {
	o.Src = &v
}

// GetLicense returns the License field value if set, zero value otherwise.
func (o *V2TaxonomyImageMetadataResponse) GetLicense() string {
	if o == nil || o.License == nil {
		var ret string
		return ret
	}
	return *o.License
}

// GetLicenseOk returns a tuple with the License field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2TaxonomyImageMetadataResponse) GetLicenseOk() (*string, bool) {
	if o == nil || o.License == nil {
		return nil, false
	}
	return o.License, true
}

// HasLicense returns a boolean if a field has been set.
func (o *V2TaxonomyImageMetadataResponse) HasLicense() bool {
	if o != nil && o.License != nil {
		return true
	}

	return false
}

// SetLicense gets a reference to the given string and assigns it to the License field.
func (o *V2TaxonomyImageMetadataResponse) SetLicense(v string) {
	o.License = &v
}

// GetAttribution returns the Attribution field value if set, zero value otherwise.
func (o *V2TaxonomyImageMetadataResponse) GetAttribution() string {
	if o == nil || o.Attribution == nil {
		var ret string
		return ret
	}
	return *o.Attribution
}

// GetAttributionOk returns a tuple with the Attribution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2TaxonomyImageMetadataResponse) GetAttributionOk() (*string, bool) {
	if o == nil || o.Attribution == nil {
		return nil, false
	}
	return o.Attribution, true
}

// HasAttribution returns a boolean if a field has been set.
func (o *V2TaxonomyImageMetadataResponse) HasAttribution() bool {
	if o != nil && o.Attribution != nil {
		return true
	}

	return false
}

// SetAttribution gets a reference to the given string and assigns it to the Attribution field.
func (o *V2TaxonomyImageMetadataResponse) SetAttribution(v string) {
	o.Attribution = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *V2TaxonomyImageMetadataResponse) GetSource() string {
	if o == nil || o.Source == nil {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2TaxonomyImageMetadataResponse) GetSourceOk() (*string, bool) {
	if o == nil || o.Source == nil {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *V2TaxonomyImageMetadataResponse) HasSource() bool {
	if o != nil && o.Source != nil {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *V2TaxonomyImageMetadataResponse) SetSource(v string) {
	o.Source = &v
}

// GetImageSizes returns the ImageSizes field value if set, zero value otherwise.
func (o *V2TaxonomyImageMetadataResponse) GetImageSizes() []V2ImageSize {
	if o == nil || o.ImageSizes == nil {
		var ret []V2ImageSize
		return ret
	}
	return o.ImageSizes
}

// GetImageSizesOk returns a tuple with the ImageSizes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2TaxonomyImageMetadataResponse) GetImageSizesOk() ([]V2ImageSize, bool) {
	if o == nil || o.ImageSizes == nil {
		return nil, false
	}
	return o.ImageSizes, true
}

// HasImageSizes returns a boolean if a field has been set.
func (o *V2TaxonomyImageMetadataResponse) HasImageSizes() bool {
	if o != nil && o.ImageSizes != nil {
		return true
	}

	return false
}

// SetImageSizes gets a reference to the given []V2ImageSize and assigns it to the ImageSizes field.
func (o *V2TaxonomyImageMetadataResponse) SetImageSizes(v []V2ImageSize) {
	o.ImageSizes = v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *V2TaxonomyImageMetadataResponse) GetFormat() string {
	if o == nil || o.Format == nil {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2TaxonomyImageMetadataResponse) GetFormatOk() (*string, bool) {
	if o == nil || o.Format == nil {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *V2TaxonomyImageMetadataResponse) HasFormat() bool {
	if o != nil && o.Format != nil {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *V2TaxonomyImageMetadataResponse) SetFormat(v string) {
	o.Format = &v
}

func (o V2TaxonomyImageMetadataResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TaxId != nil {
		toSerialize["tax_id"] = o.TaxId
	}
	if o.Src != nil {
		toSerialize["src"] = o.Src
	}
	if o.License != nil {
		toSerialize["license"] = o.License
	}
	if o.Attribution != nil {
		toSerialize["attribution"] = o.Attribution
	}
	if o.Source != nil {
		toSerialize["source"] = o.Source
	}
	if o.ImageSizes != nil {
		toSerialize["image_sizes"] = o.ImageSizes
	}
	if o.Format != nil {
		toSerialize["format"] = o.Format
	}
	return json.Marshal(toSerialize)
}

type NullableV2TaxonomyImageMetadataResponse struct {
	value *V2TaxonomyImageMetadataResponse
	isSet bool
}

func (v NullableV2TaxonomyImageMetadataResponse) Get() *V2TaxonomyImageMetadataResponse {
	return v.value
}

func (v *NullableV2TaxonomyImageMetadataResponse) Set(val *V2TaxonomyImageMetadataResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV2TaxonomyImageMetadataResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV2TaxonomyImageMetadataResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2TaxonomyImageMetadataResponse(val *V2TaxonomyImageMetadataResponse) *NullableV2TaxonomyImageMetadataResponse {
	return &NullableV2TaxonomyImageMetadataResponse{value: val, isSet: true}
}

func (v NullableV2TaxonomyImageMetadataResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2TaxonomyImageMetadataResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


