/*
NCBI Datasets API

### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 

API version: v2alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncbi-openapi-v2_goland

import (
	"encoding/json"
	"fmt"
)

// V2reportsAssemblyStatus the model 'V2reportsAssemblyStatus'
type V2reportsAssemblyStatus string

// List of v2reportsAssemblyStatus
const (
	V2REPORTSASSEMBLYSTATUS_ASSEMBLY_STATUS_UNKNOWN V2reportsAssemblyStatus = "ASSEMBLY_STATUS_UNKNOWN"
	V2REPORTSASSEMBLYSTATUS_CURRENT V2reportsAssemblyStatus = "current"
	V2REPORTSASSEMBLYSTATUS_PREVIOUS V2reportsAssemblyStatus = "previous"
	V2REPORTSASSEMBLYSTATUS_SUPPRESSED V2reportsAssemblyStatus = "suppressed"
	V2REPORTSASSEMBLYSTATUS_RETIRED V2reportsAssemblyStatus = "retired"
)

// All allowed values of V2reportsAssemblyStatus enum
var AllowedV2reportsAssemblyStatusEnumValues = []V2reportsAssemblyStatus{
	"ASSEMBLY_STATUS_UNKNOWN",
	"current",
	"previous",
	"suppressed",
	"retired",
}

func (v *V2reportsAssemblyStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V2reportsAssemblyStatus(value)
	for _, existing := range AllowedV2reportsAssemblyStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V2reportsAssemblyStatus", value)
}

// NewV2reportsAssemblyStatusFromValue returns a pointer to a valid V2reportsAssemblyStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV2reportsAssemblyStatusFromValue(v string) (*V2reportsAssemblyStatus, error) {
	ev := V2reportsAssemblyStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V2reportsAssemblyStatus: valid values are %v", v, AllowedV2reportsAssemblyStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V2reportsAssemblyStatus) IsValid() bool {
	for _, existing := range AllowedV2reportsAssemblyStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v2reportsAssemblyStatus value
func (v V2reportsAssemblyStatus) Ptr() *V2reportsAssemblyStatus {
	return &v
}

type NullableV2reportsAssemblyStatus struct {
	value *V2reportsAssemblyStatus
	isSet bool
}

func (v NullableV2reportsAssemblyStatus) Get() *V2reportsAssemblyStatus {
	return v.value
}

func (v *NullableV2reportsAssemblyStatus) Set(val *V2reportsAssemblyStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableV2reportsAssemblyStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableV2reportsAssemblyStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2reportsAssemblyStatus(val *V2reportsAssemblyStatus) *NullableV2reportsAssemblyStatus {
	return &NullableV2reportsAssemblyStatus{value: val, isSet: true}
}

func (v NullableV2reportsAssemblyStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2reportsAssemblyStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

